### ISSUE TITLE
Codereview

### ISSUE THREAD

**Issue by HansLuft778** [FJXHI/PBO-Squad-ToDo#80]
- [x] #81 
 - [x] #108
 - [x] #106
 - [x] #95
 - [x] #86
 - [x] #112
 - [x] #111
 - [x] #109
 - [x] #175 (maybe Future feature)
 - [x] #94
 - [x] #83
 - [x] #82
 - [x] #110

**Comment by FJXHI** [comment]
**### App**
- Fontsize sollte mit der Auflösung skalieren
- welche Bedeutung haben die Farben
- Angaben von Fristen und Douer konsitent sichtbar machen (bei keiner Eintragung Feld leer lassen)
- Beschreibung könnte bei wenig Text immer angezeigt werden. Einblendung bei Auswahl erscheint hier unpraktikabel
- Ausgewählte Felder sollten auch farblich hervorgehoben werden
- verwendete Farben zu intensiv

Dialog Aufgabenbearbeitung
-Design entspricht nicht dem der vorherigen Anwendung
-Cancel und Save am Ende des Dialogs
-Klicks werden weiter "nach unten" gegeben, d.h. angeklickte Aufgabe klappt auf und zu beim berühren vom Dialog
-Cancel und Save Button werden beide gedrückt, auch wenn man nur überhalb der Buttons drückt Andern und speichern bewirkt keine Anderung

Feldgröße teils so groß, dass die Informationen bei Click direkt angezeigt werden könnten > ist ein mehrwert wirklich gegeben erst nach Klick noch mehr anzuzeigen?

Im Gegensatz zu den anderen Aufgaben führt beim neuanlegen von Aufgaben das auslassen des Datums und der Daver zum Eintrag invalide oder NAN > Überprüfung der Eingaben sollte durchgeführt werden 

Im Rastermodus
-werden Buttons (Bearbeitung, Löschen, Erledigt) nach klick angezeigt (fokus geht nicht weg, jede Kachel zeigt dann alle Buttons an), Bearbeitung kann nicht gewählt werden 
-Schriftfont zu klein

Sind die Buttons zum Umschalten so wichtig, dass beide zugleich angezeigt werden müssen in der Fußleiste? (es sollte zudem e ein Toggle Button genutzt werden, der dann Umschaltet wenn man drauf klickt)

in Listenansicht kann nicht geschrollt werden

mit Suche kann ich in der Listenansicht aber Aufgaben finden, die nicht angezeigt werden

Clear-Button in Suche fenit

Modal (zB Aufgabe bearbeiten) sollte sich schließen, wenn man außerhalb klickt

Filterdialog 
-Sortierungsreiherifolge (AxZ oder Z>A) setzt sich zurück beim schließen & öffnen des Dialogs (es bleibt immer A>Z)

Design grundsätzlich etwas oltmodisch (wenn man sich an Google Fonts Icons (material design) hölt, könnte man auch nahe am material design bewegen



### **Code**

Bei installation gibt es 1 moderate vulnerability (vite 4.5.0 > Vite XSS)

Allgemein
-Fontsize mit "rem" angeben für automatische Skalierung
-Nutzung von SCSS empfehlenswert
-Nutzung von css/scss Framework wie Tailwind empfehlenswert um Styles zu vereinheitlichen und einfacher zu nutzen (verbesserung von skalierung usw)
-vieles sehr komplex gestaltet, ohne den "Need"

main.css und base.css machen es schwierig, die styles zu jedem Tag zu finden, hier könnte man z.B. "colors.css" auslagern und body html in die App vue übernehmen, Slider.css definiert noch mal css, d.h. hier ist on zwei verschiedenen stellen css zu finden? > vereinheitlichen und nur an einer stelle cas ablegent

App.vue
-RouterLink importiert, aber nicht genutat
-main solite keine position "absolut haben, das führt zu potentiellen layout problemen und vor allem ist es probelmatisch für die Barmerefreiheit > nav und footer kann fixiert sein, Main sollte am besten display block haben
-scrolling kann deaktiviert werden mit CSS falls gewünscht (absolut daher auch nicht gebraucht)

CSS
-main> left/right = 0px> angabe px ist nicht relevant und kann weggelassen werden
-3vh/8vh als angabe von höhen kann zu problemen führen, nav bar sollte om besten in px oder besser rem angegeben werden

auskommentiertes CSS sollte entfernt werden

aufruf von Funktionen in v-for sollte vermieden werden wenn eine Teilmenge von den Entries gewünscht ist, sollte diese vom Store direkt bereitgestellt werden (als computed object)

HomeView.vue
-Inline Style bei CompactEntry sollte vermieden werden (margin-bottom)

MoreView.vue
-Inline Style bei SquareEntry sollte vermieden werden
-binding von style (also die "") wird nicht gebraucht bei strings und sollte weggelossen werden statt margin-bottom beim Objekt kann im bestehenden Grid row-gap verwendet werden

Addview/Input form
-@claseaction sollte @close-action/ closeAction sein

THEInputForm/THEInputModal THE wird nicht gebraucht und auch nicht genutzt, (import InputForm onstelle von import TheinputForm

SquareEntry
-remove und done führen aktuell zum Löschen des Eintrages, sollen später die Elemente separat in Listen zur Finderauffindbarkeit abgelegt werden?
-<nav> ist dort (in <span>) nicht erlaubt, jedoch sollte nav nur einmalig (bzw einmalig für desktop und einmalig für Mobil) im Dokument vorkommen (nur die Navigationsleistel)

CompactEntry vue
-sehr viele ungenutzte Imports > sollten alle weg 
-z27>schreibfehler "backgoundColor fehlt ein R
--sehr umständlich die Forbe darzustellen und zusammen zu bauen > ggf. auf HEX werte setzen 
-Funktionsaufrufe, die nur eine andere Funktion aufrufen (delClicked/editClicked) kann weggelassen werden (redundanter code), es sollte sofort die funktion aufgerufen werden?
-<img> solite eines alt text haben
-Z104/106><nav> ist dort (in <span>) nicht erlaubt, jedoch solite nav nur einmalig (bzw. einmalig für desktop und einmalig für Mobil) im Dokument vorkommen (nur die Navigationsleiste!)
-ungenutztes oss sollte entfernt werden (auskommentierter Template teil beinhaltet css was nicht mehr gebraucht wird

FilterModal vue
-props werden nicht genutzt
-SortSetting könnte/sollte mit v-for schleife geschrieben werden
-button könnte/sollte als eigene Komponente genutzt werden
-Farbdefinitionen sind auch hier zu finden > schwierig zu nutzen
